config/routes.rb
Rails.application.routes.draw do
  resources :events
  devise_for :users, controllers: { registrations: "users/registrations", omniauth_callbacks: 'omniauth_callbacks' }
  
  

   root 'users#home'

   resources :users
   
   match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup   
   

end

app/models/user.rb
class User < ActiveRecord::Base
  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable, :omniauthable

  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update
  validates_presence_of :name
  validates_format_of :email, :with => Devise::email_regexp, on: :create
  
  has_many :events

  def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          name: auth.extra.raw_info.name,
          #username: auth.info.nickname || auth.uid,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20]
        )
        #user.skip_confirmation!
        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
     devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation)}
  end
  
  protected
  def after_signup_path_for(user)
    user_path(user)    
  end 


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!, except: [:home]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  
  def home

  end

  # GET /users
  # GET /users.json
  def index
    #show all users only if logged in user is an admin
    if current_user.admin
      @users = User.all
    else
      @users = [ current_user ]
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    Rails.logger.info "In create method"
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  #for FB signup
  # GET/PATCH /users/:id/finish_signup
  def finish_signup
    # authorize! :update, @user 
    if request.patch? && params[:user] #&& params[:user][:email]
      @user = User.find(params[:id])
      if @user.update(user_params)       
        sign_in(@user, :bypass => true)
        redirect_to @user, notice: 'Your profile was successfully updated.'
      else
        @show_errors = true
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user, html: {class: 'form-horizontal'}) do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4><%= pluralize(@user.errors.count, "error") %> prohibited this contact from being saved:</h4>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name, class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, autofocus: true, class:"form-control" %>
    </div>  
  </div>

  <div class="field form-group">
    <%= f.label :email, class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.email_field :email, autofocus: true, class:"form-control" %>
    </div>  
  </div>  
  
  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Save", class: 'btn btn-primary' %>
    </div>  
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-xs-12 border-form-div"> 

		<h3>Edit User</h3>

		<%= render 'form' %>

		<%= link_to 'Show', @user %> |
		<%= link_to 'Back', users_path %>
	</div>
</div>

app/views/users/finish_signup.html.erb
<div id="add-email" class="container">
  <h1>Add Email</h1>
  <%= form_for(current_user, :as => 'user', :url => finish_signup_path(current_user), :html => { role: 'form'}) do |f| %>
    <% if @show_errors && current_user.errors.any? %>
      <div id="error_explanation">
        <% current_user.errors.full_messages.each do |msg| %>
          <%= msg %><br>
        <% end %>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :email %>
      <div class="controls">
        <%= f.text_field :email, :autofocus => true, :value => '', class: 'form-control input-lg', placeholder: 'Example: email@me.com' %>
        <p class="help-block">Please confirm your email address. No spam.</p>
      </div>
    </div>
    <div class="actions">
      <%= f.submit 'Continue', :class => 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/users/home.html.erb
<div class="row">
  <div class="col-xs-12 border-form-div">     
    <%= image_tag "security.jpg"  %>
  </div>
</div>

app/views/users/index.html.erb
<h3>Listing Users</h3>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Change Password', edit_user_registration_path %></td>
        <% if current_user.admin || user == current_user %>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <% end %>
        <% if !user.admin %>
        <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.admin? %>
  <%= link_to 'New User', new_user_path, class: "btn btn-primary" %>
<% end %>

app/views/users/new.html.erb
<div class="row">
  <div class="col-xs-12 border-form-div"> 

	<h3>Add New User</h3>
	<%= render 'form' %>
	<%= link_to 'Back', users_path %>
  </div>
</div>

app/views/users/show.html.erb
<h3>Hi <%= current_user.name %>!</h3>
<p> Track your important events and dates here.. and we would make sure you nevernever miss them again! </p> 

<%= link_to "Add an Event", new_event_path,  class: "btn btn-primary" %> &nbsp; <%= link_to "Update Profile", users_path,  class: "btn btn-primary" %>
<br>